graph: graph.c
	gcc -c myMath.c charLines.c graph.c
	gcc -o graph -lm myMath.o charLines.o graph.o

graph2: graph2.c
	gcc -c myMath.c charLines.c graph2.c
	gcc -o graph -lm myMath.o charLines.o graph2.o
