#!/usr/bin/env bash
set -e

# This script generates header files for C source files.

[[ -z "$1" ]] && $(echo "filename required"; exit 1)

header_file="$(echo $1 | rev | cut -c 3- | rev).gen.h"

echo "This header file generated by $0" "$header_file"

IFS=$'\n'

# Identifiers: [A-z], digits, pointers, undercores
# Then our regex is: identifier identifier(identifier, identifier) {
for dec in $(grep -Po '(\w|\d|\*|\_)+ (\w|\d|\*|\_)+\((\w|\d|\*|\_|\,| )+\) \{' "$1"); do
  # cut the {, add a ;, and echo it into the header
  echo "$dec" | rev | cut -c 3- | rev | echo "$(cat -);" >> "$header_file"
done
