include ../library.mk

.PHONY: build
build: bit-palindromes decimal-sum mergesort transpose

.PHONY: test
test:; exit 0

# targets
$(call build,bit-palindromes)
$(call build,decimal-sum)
$(call build,mergesort)
$(call build,transpose)
